development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: meu_teste
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: meu_teste_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: meu_teste_production
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
